### PR TITLE
Update Dockerfile with Laravel PHP extensions needed

### PR DESCRIPTION
**Pull request by insign**
Based on https://laravel.com/docs/10.x/deployment#server-requirements

I think it is relevant since is the most popular framework these days.

xmlwriter is needed for Laravel Sanctum.

### CODE REVIEW

**Comment by insign** [comment]
Related to #148

**Comment by TrafeX** [comment]
Hi @insign ,

Thank you for your contribution. Although I hold back on adding extensions to keep the base image as small as possible, these extensions are part of what's bundled with PHP (except for xmlwriter, but we also have xmlreader so it's not adding any overhead). So I'll be happy to merge this!

**Comment by insign** [comment]
I truly understand that you want a very simple and clean image but have composer looks like a must. I saw in the documentation how to add but keeps the sensation that is so needed because even small projects should rely on composer to keeps thinks tidy.

**Comment by insign** [comment]
And... like others images since the deploy is automated could gave a image**-dev** with debug enable by default (even I not use it)

**Pull request merged**
